ShopApp/Controllers/AdvertisementsController.cs
using AutoMapper;
using BusinessLogic.DTOs;
using BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopApp.Data;
using ShopApp.Data.Entities;
using ShopApp.Helpers;
using System.Security.Claims;

namespace ShopApp.Controllers
{
    public class AdvertisementsController : Controller
    {
		private readonly IAdvertsService advertsService;
		private readonly IMapper mapper;
        private string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier)!;
        public AdvertisementsController(IAdvertsService advertsService, IMapper mapper)
        {
            this.advertsService = advertsService;
            this.mapper = mapper;
		}
        private void LoadCategories()
        {
            ViewBag.Categories = new SelectList(advertsService.GetAllCategories(), nameof(Category.Id), nameof(Category.Name));
		}
        private void LoadConditions()
        {
            ViewBag.Conditions = new SelectList(advertsService.GetAllConditions(), nameof(Condition.Id), nameof(Condition.Name));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(advertsService.GetAll());
        }

        [AllowAnonymous]
        public IActionResult MyAdvertisements()
        {
            return View("Index", advertsService.GetByUser(UserId));
        }

        public IActionResult Create()
        {
            LoadCategories();
            LoadConditions();
            return View();
        }

        [HttpPost]
        public IActionResult Create(AdvertisementDto advertisement)
        {
			advertisement.Views = 0;
			advertisement.PublicationDate = DateTime.Now;
            advertisement.SellerId = UserId;
			if (!ModelState.IsValid)
            {
                LoadConditions();
                LoadCategories();
                return View();
            }
            advertsService.Create(advertisement);
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(MyAdvertisements));
            }
		}
        [AllowAnonymous]
        public IActionResult Details(int id, string? returnUrl)
        {
            var advert = advertsService.Get(id);
            if (advert == null) return NotFound();

            ViewBag.ReturnUrl = returnUrl;

            return View(advert);
        }

		public IActionResult Edit(int id)
		{
			var advert = advertsService.Get(id);
			if (advert == null) return NotFound();
			LoadConditions();
			LoadCategories();
			return View(advert);
		}

		[HttpPost]
		public IActionResult Edit(AdvertisementDto model)
		{
			if (!ModelState.IsValid)
			{
				LoadConditions();
				LoadCategories();
				return View();
			}

			advertsService.Edit(model);

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(MyAdvertisements));
            }
        }

		public IActionResult Delete(int id)
		{
			advertsService.Delete(id);
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(MyAdvertisements));
            }
        }
	}
}

ShopApp/Controllers/CartController.cs
using BusinessLogic.Interfaces;
using BusinessLogic.DTOs;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Helpers;

namespace ShopApp.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService cartService;
        public CartController(ICartService cartService)
        {
            this.cartService = cartService;
        }
        public IActionResult Index(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(cartService.GetAdverts());
        }

        public IActionResult Add(int id, string returnUrl)
        {
            cartService.Add(id);
            return Redirect(returnUrl);
        }

        public IActionResult Remove(int id, string returnUrl)
        {
            cartService.Remove(id);
            return Redirect(returnUrl);
        }
    }
}

ShopApp/Controllers/OrdersController.cs
using BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ShopApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrdersService ordersService;
        private string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier)!;
        public OrdersController(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }
        public IActionResult Index()
        {
            return View(ordersService.GetAllByUser(UserId));
        }

        public async Task<IActionResult> Create(int id)
        {
            await ordersService.Create(UserId, id);
            TempData["ToastMessage"] = "Order confirmed successfully!";

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopApp/Views/Shared/AdvertisementCard.cshtml
@inject ICartService cartService;
@using BusinessLogic.DTOs;
@using BusinessLogic.Interfaces;
@model AdvertisementDto
<div class="card">
    <a class="home-card" asp-controller="Advertisements" asp-action="Details" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path">
        <img src="@Model.ImageUrl"  alt="Advertisement Image">
    </a>
    <div class="card-body h-100 home-card">
        <div class="d-flex justify-content-between">
            <h5 class="card-title">
                <a asp-controller="Advertisements" asp-action="Details" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path" >@Model.Name</a>
            </h5>
            <div>
                @if (cartService.IsExists(Model.Id))
                {
                    <a asp-controller="Cart" asp-action="Remove" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path" class="bi bi-heart-fill"></a>
                }
                else
                {
                    <a asp-controller="Cart" asp-action="Add" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.Path" class="bi bi-heart"></a>
                }
            </div>
        </div>
        <h5 class="card-title">@Model.Price $</h5>
        <p class="card-text">@Model.LocationName</p>
        <p class="card-text"><small class="text-body-secondary">@Model.PublicationDate</small></p>
        <div>
            <a asp-controller="Orders" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-success mt-3">Order</a>
        </div>
    </div>
</div>

ShopApp/Views/Shared/_InputEditorPartial.cshtml
<script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>

<script>
    var editor = new FroalaEditor('@Model.Selector');
</script>

ShopApp/Views/Shared/_Layout.cshtml
@using BusinessLogic.Interfaces
@using Microsoft.AspNetCore.Identity
@inject ICartService cartService;
@inject SignInManager<User> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopApp.styles.css" asp-append-version="true" />
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Advertisements" asp-action="Index">Advertisements</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                        }
                    </ul>
                        <a class="bi bi-heart" asp-area="" asp-controller="Cart" asp-action="Index"></a>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <div class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advertisements" asp-action="MyAdvertisements">My Advertisements</a>
                        </div>
                    }
                        
                        <partial name="_LoginPartial" />
                   
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ShopApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>